### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by dupuchba** [dunglas/api-platform#8]
Hello @dunglas ,

I really like the work you've done with api-platform.
I'd like to know what is the roadmap and how can I help to make it better ?

Thx,

Cheers,

Baptiste

**Comment by dunglas** [comment]
Hi @dupuchba and thanks for your proposal! Any help is very welcome and there is a ton of things to do.
Our focus is currently on ApiBundle, some architecture changes are in progress: https://github.com/dunglas/DunglasApiBundle/issues

The roadmap:
1. Improve the quality (fix issues raised by Scrutinizr https://scrutinizer-ci.com/g/dunglas/DunglasApiBundle/ a notation > 9/10 is the goal)
2. Increase the unit test coverage (both in DunglasApiBundle, > 80% is the goal), needed for php-schema too
3. Implement the ADR pattern instead of current controllers
4. Decouple from Hydra
5. Rename `Resource` to `ResourceType` and make it immutable as done for metadata (dunglas/DunglasApiBundle#180)
6. Add a configuration system (dunglas/DunglasApiBundle#185)
7. Create a library containing all Symfony independent code (JSON-LD and Hydra serializers...) and make the bundle use that library
8. Last but not least, move every repositories to the org https://github.com/api-platform and change namespace of all projects from `Dunglas` to `ApiPlatform`

Some non-coding tasks are also in progress:
* a dedicated website (the web design is done, it must be integrated and developed using https://github.com/dunglas/calavera)
* more doc: https://github.com/dunglas/api-platform-doc / https://github.com/dunglas/DunglasApiBundle/tree/master/Resources/doc / https://github.com/dunglas/php-schema/tree/master/doc

If you need any help or guidance, feel free to contact me.

**Comment by dupuchba** [comment]
Ok, I will find some time during my holiday next month :-). By the way, you should put this roadmap in some .md file !

**Comment by MLKiiwy** [comment]
Yeah, it's a good roadmap ! 

But maybe add suggestion : 
4. Decouple from Hydra => Maybe also decouple from Doctrine ?

**Comment by dunglas** [comment]
In fact Doctrine is already decoupled. The remaining work should be limited to `composer.json` tweaking: #177

**Comment by dupuchba** [comment]
https://github.com/dunglas/DunglasApiBundle/issues/177
